name: Publish to PyPI

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    # Install system-level dependencies
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz libgraphviz-dev

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        poetry --version

    - name: Install dependencies
      run: |
        poetry install --without dev --no-root

    - name: Package Distribution
      run: |
        poetry build

    - name: Publish Package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
